// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) ansi 

package android.broadcast;


public interface IMtvOneSegServiceListener
{

    public abstract void onServiceNotify(int i, int j, int k, Object obj);

    public static final int CMD_BASE = 100;
    public static final int CMD_CANCEL_SCAN = 108;
    public static final int CMD_CAPTION_DATA = 129;
    public static final int CMD_CAPT_FRAME = 106;
    public static final int CMD_CLOSE = 117;
    public static final int CMD_CREATE = 101;
    public static final int CMD_DELETE = 118;
    public static final int CMD_OPEN = 102;
    public static final int CMD_PAUSE = 109;
    public static final int CMD_PLAY = 114;
    public static final int CMD_REC_CANCEL = 104;
    public static final int CMD_REC_CLOSE = 128;
    public static final int CMD_REC_OPEN = 127;
    public static final int CMD_REC_START = 103;
    public static final int CMD_REC_STOP = 105;
    public static final int CMD_REGISTER_CLIENT = 123;
    public static final int CMD_REPOSITION = 112;
    public static final int CMD_RESUME = 110;
    public static final int CMD_SCAN = 107;
    public static final int CMD_STATUS_UPDT = 113;
    public static final int CMD_TRICKMODE = 111;
    public static final int CMD_TUNER_POWER_CTRL = 125;
    public static final int CMD_TVLINK_AFFI_DEL = 121;
    public static final int CMD_TVLINK_BROADCAST_AREA_DEL = 122;
    public static final int CMD_TVLINK_DEL = 119;
    public static final int CMD_TVLINK_DEL_ALL = 120;
    public static final int CMD_TVLINK_START = 115;
    public static final int CMD_TVLINK_STOP = 116;
    public static final int CMD_UNREGISTER_CLIENT = 124;
    public static final int CMD_UPDATE_TV_FILES = 126;
    public static final String MEM_LOC_EXTRENAL = "/mnt/extSdCard/video/MyTvFiles/";
    public static final String MEM_LOC_INTERNAL = "/sdcard/video/MyTvFiles/";
    public static final int MEM_STORE_EXTRENAL = 0;
    public static final int MEM_STORE_INTERNAL = 1;
    public static final int PTYPE_BASE = 0;
    public static final int PTYPE_IMAGE = 5;
    public static final int PTYPE_LIVE = 2;
    public static final int PTYPE_LOCAL = 1;
    public static final int PTYPE_RECORD = 6;
    public static final int PTYPE_TESTMODE = 4;
    public static final int PTYPE_TVLINK = 3;
    public static final int REC_AV_ONLY = 1;
    public static final int REC_FULL = 2;
    public static final int REMOTE_CMD_BASE = 300;
    public static final int REMOTE_CMD_CANCEL_SCAN = 308;
    public static final int REMOTE_CMD_CAPTION_DATA = 327;
    public static final int REMOTE_CMD_CAPTURE_FRAME = 320;
    public static final int REMOTE_CMD_CLEANUP = 311;
    public static final int REMOTE_CMD_CLOSE = 317;
    public static final int REMOTE_CMD_CREATE = 301;
    public static final int REMOTE_CMD_DELETE = 318;
    public static final int REMOTE_CMD_DEL_TV_FILE = 306;
    public static final int REMOTE_CMD_GET_SIGNAL_STAT = 312;
    public static final int REMOTE_CMD_OPEN = 302;
    public static final int REMOTE_CMD_PAUSE = 309;
    public static final int REMOTE_CMD_PLAY = 314;
    public static final int REMOTE_CMD_REC_CANCEL = 304;
    public static final int REMOTE_CMD_REC_CLOSE = 322;
    public static final int REMOTE_CMD_REC_OPEN = 321;
    public static final int REMOTE_CMD_REC_START = 303;
    public static final int REMOTE_CMD_REC_STOP = 305;
    public static final int REMOTE_CMD_REPOSITION = 326;
    public static final int REMOTE_CMD_RESUME = 310;
    public static final int REMOTE_CMD_SCAN = 307;
    public static final int REMOTE_CMD_SET_SVC_STATE = 319;
    public static final int REMOTE_CMD_STATUS_UPDT = 313;
    public static final int REMOTE_CMD_TRICKMODE = 325;
    public static final int REMOTE_CMD_TVLINK_START = 315;
    public static final int REMOTE_CMD_TVLINK_STOP = 316;
    public static final int SIGNAL_BASE = 0;
    public static final int SIGNAL_LOW = 1;
    public static final int SIGNAL_NO = 2;
    public static final int SIGNAL_NORMAL = 0;
    public static final int STAT_AUDIO_TRACK_CHANGED = 234;
    public static final int STAT_BASE = 200;
    public static final int STAT_BUFFERING_BEGIN = 204;
    public static final int STAT_BUFFERING_END = 206;
    public static final int STAT_BUFFERING_PROGRESS = 205;
    public static final int STAT_CANNOT_RECORD = 227;
    public static final int STAT_CAPT_DATA = 211;
    public static final int STAT_CHANNELINFO_UPDATE = 232;
    public static final int STAT_DEL_FILE = 218;
    public static final int STAT_END_OF_FILE = 214;
    public static final int STAT_FAILURE = 203;
    public static final int STAT_FRAME_READY = 233;
    public static final int STAT_INSUFFICIENT_MEMORY = 217;
    public static final int STAT_MEDIA_ERROR = 207;
    public static final int STAT_NIT_RCV = 228;
    public static final int STAT_NO_OF_AUDIOPID = 226;
    public static final int STAT_OUT_OF_MEMORY = 216;
    public static final int STAT_PMT_CHANGE = 223;
    public static final int STAT_PMT_RCV = 225;
    public static final int STAT_PROGINFO_UPDT = 208;
    public static final int STAT_PROGRESS = 202;
    public static final int STAT_PRSR_EIT_RCV = 220;
    public static final int STAT_PRSR_NIT_RCV = 221;
    public static final int STAT_PRSR_PMT_RCV = 219;
    public static final int STAT_REC_FRAME_READY = 231;
    public static final int STAT_RMP_SETUP_DONE = 230;
    public static final int STAT_RMP_SETUP_START = 229;
    public static final int STAT_SIGNAL_UPDT = 210;
    public static final int STAT_STREAMTIME_UPDT = 209;
    public static final int STAT_SUCCESS = 201;
    public static final int STAT_TIME_UPDT = 212;
    public static final int STAT_TUNER_LOW_SIGNAL = 222;
    public static final int STAT_UNKNOWN = 215;
    public static final int STAT_VIDEO_RATIO_UPDT = 213;
    public static final int TRICK_FW = 2;
    public static final int TRICK_MODE_FW = 2;
    public static final int TRICK_MODE_RW = 3;
    public static final int TRICK_MODE_STOP = 0;
    public static final int TRICK_RW = 2;
    public static final int TRICK_SPEED_ONE_X = 0;
    public static final int TRICK_SPEED_TEN_X = 2;
    public static final int TRICK_SPEED_TWO_X = 1;
    public static final int TRICK_STOP = 0;
}
